### ISSUE TITLE
Helm chart for WebGoat/WebWolf

### ISSUE THREAD

**Issue by AndyG-0** [WebGoat/WebGoat#1051]
This would be an enhancement and probably a new repo/helm repo. The idea would be to take the existing Docker Image and be able to deploy it on to Kubernetes using a Helm Chart. I'm hoping this can start the discussion on where to store it etc. I have a working example in an internal repo which I can contribute as a start.

**Comment by zubcevic** [comment]
Some time ago I was also experimenting with a helm chart. There is a branch that contains a sample. 
https://github.com/WebGoat/WebGoat/tree/helm/platformQuickStarts/helm

But in order to run WebGoat and WebWolf together in a Kubernetes environment, we will need some more drastic changes in WebGoat. Also you will need a more complex helm chart than my simple version.

WebGoat is stateful and uses cookies. And lots of exercises depend on this. Also you need to think about how persistent volumes need to be configured. And the database would need to be a stateful service if you want to use multiple pods.

If you just want to run it as a single all-in-one-pod, you can do so as described here: https://zubcevicdotcom.wordpress.com/owasp-webgoat/deploying-webgoat-on-openshift/ and there is really no need for a helm chart.

Anyway, if we would want helm chart support, we should probably maintain that in a separate repository. Such as the one with the ansible role for WebGoat

**Comment by AndyG-0** [comment]
We should be able to use an ingress to support cookies. The helm chart I have built uses two ingresses which talk to two services that map to webgoat and webwolf. We should be able to support cookies through the use of ingresses unless I'm missing something. Please let me know if I am. 

I've thrown the helm chart up here: https://github.com/AndyG-0/helm-goatandwolf/ This has the configuration for the two ingresses. I do not have the pvc configured. If we were to add one, what should be the mount points? We should be able to mount them pretty easily. I also need to do more testing to make sure everything is working properly. If I have time this weekend I will try to put it on my k3s pi cluster and run it. I don't think I was thinking about multiple pods at this time. One pod is fine for now I would think but it might be something to think about in the future.

**Comment by AndyG-0** [comment]
I had another issue #1052 which was kind of tied to this. I will need to probably build my own armv7 arch image to be able to test so it's going to take a little longer to test on my k3s cluster. The chart has however already been tested on amd64 and it looks like it's working fine. I believe I need to bump the memory to 1GB do to oom issues. Not sure what is a fair amount of memory to give to it.

**Comment by zubcevic** [comment]
See #1197 for a working Helm Chart for OpenShift Kubernetes clusters. This works and required one fix in WebWolf. This example is requiring OpenShift since some of the Yaml templates refer to extensions in OpenShift.

**Comment by zubcevic** [comment]
Here is a working Helm chart for running the new and refactored webgoat image on openshift
