### ISSUE TITLE
Minor: Change default IP to avoid OWASP ZAP port conflict

### ISSUE THREAD

**Issue by davewichers** [WebGoat/WebGoat#1127]
Both OWASP WebGoat and OWASP ZAP default to using port 8080 I believe.  Can we change the default to be something non-conflicting so when you want to use them together they 'just work'?

Like port 8081 or something?  This isn't a huge deal, but would be easy to change (I believe). If a change is made, we should probably research commonly used default ports like this and try to avoid all of them.

This isn't a huge deal. Just an idea.

**Comment by aolle** [comment]
Hello, I would like to share with you my 2¢ about this issue.

The 8080 port has been a common alternative HTTP port used for web applications in general, because it's above the restricted ports. And of course, it can also be used for HTTP web proxies like ZAP.

But, in the point of view of a practical scenario, do you think that an application has to be adapted because of a web proxy existence, or it should be the opposite? ZAP is a tool more focused on the client/user side.

WebGoat, like many other applications (like ZAP), provides an easy way for changing the listening port.

OWASP are "suggesting" here
https://www.zaproxy.org/faq/how-do-you-configure-zap-to-test-an-application-on-localhost/
In case of conflict, ZAP listening port can be changed easily.

Also please, consider that there are many (tons) of articles, tutorials, comments, etc over the internet referencing the WebGoat default 8080 port.

I see your point, but forcing that change we are, in some way, "coupling" those apps.

WDYT?

**Comment by davewichers** [comment]
Actually, if you start WebGoat first, and THEN start ZAP, ZAP automatically detects the port conflict (which is cool) and offers to change its listening port to the next available port. As such, I think it might indeed be better to NOT change the default, due to all the existing articles/people are used to it, etc. So, I'm OK with us closing this, with a 'no change'.

**Comment by aolle** [comment]
Thank you for your response. I will go ahead and close this issue.
