### ISSUE TITLE
Forced browsing lesson does not show success

### ISSUE THREAD

**Issue by nbaars** [WebGoat/WebGoat#143]
If you use the url: `http://localhost:8080/WebGoat/conf` for the solution you will see the following address: `http://localhost:8080/WebGoat/login.mvc#attack/150/1400&succeeded=yes` however this takes you to a login page instead of success page:
 
<img width="479" alt="capture" src="https://cloud.githubusercontent.com/assets/493861/10834268/356fa3aa-7e98-11e5-99f3-4082f3a5961b.PNG">

**Comment by misfir3** [comment]
Since the container acts as SPA now this one is a bit trickier. Here are my ideas ...

* Remove the category/lesson for now
* Configure a route (server-side) for /conf that can trigger success on this lesson & instruct user to open that page in a new tab/window and then return here.
* 'Spoof' the lesson entirely in the client
* Create a 'route' in the client that triggers the success, but returns user to the original page/route. 
The last two require tight coupling of container to content (or special features to facilitate that content), which breaks the plug-in approach

Thoughts/questions?

**Comment by misfir3** [comment]
alternatively, if we can get /conf to redirect to ...
http://localhost:8080/WebGoat/**start.mvc**#attack/{lesson#}/{cat#}&succeeded=yes
as opposed to login.mvc, that will do the trick. Started to look at it, but am out of time for today

**Comment by nbaars** [comment]
Fixed, found out that the conf servlet and jsp were still part of the WebGoat container. This is now part of the lesson and the container during startup looks for servlets and dynamically adds them to the container. 

The servlet now redirects to the lesson which displays the success page.

**Comment by nbaars** [comment]
I will create a pull request after we release version 7.0
