### ISSUE TITLE
Webwolf error 500 when uploading files

### ISSUE THREAD

**Issue by fearcube69** [WebGoat/WebGoat#1473]
When uploading files to webwolf I got a 500 response which was an internal server error. In the command line there was error as in screenshot below. My configuration were as below:

os: ubuntu 22.04
webgoat version : webgoat-2023.4.jar
java version : jdk-18

![Screenshot 2023-04-12 025753](https://user-images.githubusercontent.com/63183005/231263346-4429cee9-41e2-4319-9783-98498173d66a.png)
![Screenshot 2023-04-12 025857](https://user-images.githubusercontent.com/63183005/231263365-0b204d96-d034-4a38-bfd1-ea782d169c93.png)

**Comment by DimitriLachman** [comment]
im having the same issue, is there any updates towards the fix?

**Comment by aolle** [comment]
I reviewed the logs that were shared, but unfortunately, I have not been able to reproduce the exact problem you mentioned.

In order to further investigate and provide a comprehensive solution, I kindly request that you share the complete logs. It would be helpful to have access to the full log files, including any relevant error messages or stack traces. Additionally, providing more information such as the type of file involved, its size, the version of WebGoat you are using, and any other pertinent details would greatly assist in the troubleshooting process.

By gathering this additional information, we can delve deeper into the issue and work towards finding a resolution. Please understand that the more specific and detailed the information provided, the better equipped I will be to analyze and address the problem effectively.

**Comment by nbaars** [comment]
@DimitriLachman in your screenshot looks like ZAP is running as well?
