### ISSUE TITLE
Quiz not showing

### ISSUE THREAD

**Issue by vstkl** [WebGoat/WebGoat#1753]
In quiz data is not showing, i don't know if it's intentional or not, but it feels like its not, since the questions_cia.json is available. https://IP:PORT/WebGoat/start.mvc#lesson/CIA.lesson/4

**Comment by nikgreg99** [comment]
Yeah they have fix this problem if you see the commit list, I have opened personally this issue, but if you are using a Docker Image you are using the last one that is pretty old.

**Comment by cap-dev0x** [comment]
Greetings! This sounds similar to an issue that was solved earlier, #1703  - this issue was resolved by #1736 . However, this fix was implemented after the latest release was published. If you would like to implement the fix, I suggest building locally. You can find the instructions on how to in Section 4 of the [README](https://github.com/WebGoat/WebGoat/blob/main/README.md). I've also attached the commands for the clean install below: 
```
# On Linux/Mac:
./mvnw clean install

# On Windows:
./mvnw.cmd clean install

# Using docker or podman, you can than build the container locally
docker build -f Dockerfile . -t webgoat/webgoat
```

**Comment by harmin-parra** [comment]
The proposed solution doesn't work
```
./mvnw clean install
bash: ./mvnw: No such file or directory
```

**Comment by boly38** [comment]
The proposed solution works for me after a `spotless:apply`
````
$ mvn spotless:apply
$ ./mvnw.cmd clean install -DskipTests
````

(I'll maybe suggest a compose file to avoid loosing progress on each docker restart)
Of course it would be nice to have fresh docker image

thanks for this nice project 👍

**Comment by abhishekgoldypathak** [comment]
building dockerfile locally gave error in STEP 6

`Step 6/12 : COPY --chown=webgoat target/webgoat-*.jar /home/webgoat/webgoat.jar
COPY failed: no source files were specified
                                                                             
-[~/Downloads/WebGoat]
 
`
Are there other known ways to tackle this - the docker image seems 2+ years old.
