### ISSUE TITLE
Http Basics - minor edits and change completion state

### ISSUE THREAD

**Issue by mayhew64** [WebGoat/WebGoat#178]
Lesson requires 3 submits to complete, we should change it to 2 submits so it completes after 2 round trips.  

First submit reverses test
Second submit reverses it back and completes the lesson.

The reference to OWASP Zap should be a link if possible

**Comment by span** [comment]
The logic behind the number of submits uses the lesson tracker count for visits. This means that if the lesson is restarted it will only take one submit to complete the lesson if it has been previously completed.

```
if (!person.toString().equals("") && getLessonTracker(s).getNumVisits() > 3) {
    makeSuccess(s);
}
```

Since the user has completed it before it seems it is not a great deal but it is not consistend and perhaps could be changed as well.
