### ISSUE TITLE
Lessons are unavailable

### ISSUE THREAD

**Issue by MGTHEBOSS** [WebGoat/WebGoat#273]
I downloaded `webgoat-container-7.0.1.war` file from the `releases` page, renamed it to `WebGoat.war`, and moved it to `$CATALINA_HOME/webapps`. I can log in from `localhost:8080/WebGoat/attack`, but after I log in I don't see any lessons on the left. I have checked `#32`, `#242`, `#254`, & `#268`. The jar files are in `plugin-lessons`. The URL `http://localhost:8080/WebGoat/service/lessonmenu .mvc` gives `[{"name":"Admin Functions","type":"CATEGORY","children":[{"name":"Report Card","type":"LESSON","children":[],"complete":false,"link":"#attack/16/2000"}],"complete":false,"link":null}]`.

![screenshot](https://cloud.githubusercontent.com/assets/3612991/20350973/f1599d74-ac36-11e6-8143-ff85960f59c5.jpg)

**Comment by span** [comment]
Would you mind trying again with the new 7.1 release. Could you also try to login as both guest and admin to se if there is a difference in behaviour?

**Comment by MGTHEBOSS** [comment]
@span I tried with the new 7.1 release and got same results. In the case of admin, I see some extra options but not the lessons. 
![screenshot](https://cloud.githubusercontent.com/assets/3612991/20481974/ee160210-b00f-11e6-9ed2-086e166d60ba.jpg)

**Comment by mayhew64** [comment]
Which Browser are you Using? I have had troubles with chrome and 7.0.1exhibiting the missing lessons.

**Comment by MGTHEBOSS** [comment]
@mayhew64 I am using Iceweasel.

**Comment by dougmorato** [comment]
He is right..... exec.jar is working as expect.  WAR file seems not to be working. 

I am investigating why, as they were both generated ad same time

**Comment by span** [comment]
Interesting. I downloaded the 7.1 vesion and the latest tomcat last night and I got it working immediately with the 7.1 from the release page. I was on a Mac using Firefox and Chrome.

**Comment by mordwin1** [comment]
'm having the same issue as MGTHEBOSS I loaded WebGoat  7.1 onto a Linux OS running tomcat 9 and while the java files for the lessons are loaded into the plugin_lessons dir i don't seem to have a menu item on the main page after login to load them.

**Comment by nbaars** [comment]
Tested Tomcat 9 and there is an issue with the classloader

```
java.util.concurrent.ExecutionException: java.lang.ClassCastException: org.apache.catalina.loader.ParallelWebappClassLoader cannot be cast to org.apache.catalina.loader.WebappClassLoader
```
Are you able to use the standalone version?

**Comment by mordwin1** [comment]
Nanne,
Thanks for the feedback I can run the standalone version, I was just trying to get the version that ran on tomcat working and the problem was troubling me. Do you know if WebGoat will run on tomcat 8 or do you have to roll back to 7 to get it to run. I suppose for now I can just use the standalone version and when the other one if fixed I can switch. One the plus side I have learned a lot about tomcat.

**Comment by nbaars** [comment]
There are two issues at hand:

1) Tomcat 8 and above uses a different classload which can be fixed with a change in the context.xml
2) The method signature of addJars() has changed in Tomcat 8 and above.

So even if we fix 1 (as a FAQ) we still have issue 2 which can only be fixed with a code change.
For now I've added an entry to our FAQ (https://github.com/WebGoat/WebGoat/wiki/FAQ#tomcat)

**Comment by nbaars** [comment]
Also see #300

**Comment by nbaars** [comment]
Closing, since the release of version 8.0 we no longer actively support version 7.1.

**Comment by sohelero** [comment]
I was having exactly the same issue of not seeing the lessons. I tried out different things but nothing worked. Then I tried something very different and could make the lessons available at last. Please follow the steps:
1. Download the latest WebGoat release from https://github.com/WebGoat/WebGoat/releases
2.  Run the command in the folder where you downloaded everything. Most probably your Download folder.
in Kali Linux, go to Download Folder and execute the following command:
root@kali:~Download# java -jar webgoat-server-8.0.0.VERSION.jar [--server.port=8080] [--server.address=localhost]
VERSION can be M21 or whatever you find to be the latest. So, the command will be 
java -jar webgoat-server-8.0.0.M21.jar [--server.port=8080] [--server.address=localhost]

By default WebGoat starts on port 8080 with --server.port you can specify a different port. With server.address you can bind it to a different address (default localhost)

If you use Java 9 or higher you need to run WebGoat as follows:
java --add-modules java.xml.bind -jar webgoat-server-8.0.0.VERSION.jar

In order to check the version of Java, run the command
java -version

Hopefully it will work this time. All the best.
Sohel 
ero007@yahoo.com

**Comment by AkshayShetty23** [comment]
Install JRE in your system and that will work. lessons will be loaded
