### ISSUE TITLE
By default binds to ALL network interfaces

### ISSUE THREAD

**Issue by FlorianLoch** [WebGoat/WebGoat#431]
If I am not completely missing something, the current release binds to ALL NETWORK INTERFACES by default.

I accessed the login page via localhost and the address assigned to me by my local network - the latter should not work. I used the standalone approach.

This is really dangerous, especially when stating the opposite in the readme.

Could someone please verify this?

**Comment by nbaars** [comment]
Correct, by default Spring Boot binds to 0.0.0.0. You can change this behavior on the command line, see https://github.com/WebGoat/WebGoat/wiki/FAQ:

```
java -jar webgoat-server-<<version>>.jar --server.port=8080 --server.address=127.0.0.1
```

I've added this behavior now as default to our application.properties.

**Comment by FlorianLoch** [comment]
@nbaars Thank you for verifying this. 

I invoked myself like told in the FAQ, but I think it needed verfication and a fix ;)

**Comment by nbaars** [comment]
Binding to localhost is now default since v.8.0.0.M10

Thanks for reporting.

**Comment by hexfred** [comment]
This fix has an unfortunate a side effect on the WebGoat docker image.
It is now no more possible to connect on the container from the host, even if exposing the port with the docker run -p option.
@nbaars, maybe this issue could be fixed by using the sprint boot --server.address=0.0.0.0 in the start.sh script in the docker image, as you mentioned before.

**Comment by nbaars** [comment]
@hexfred thanks, indeed you are right. I've created a new version v.8.0.0.M11 the Docker image should work again

**Comment by hexfred** [comment]
@nbaars. Thx for the fix. The docker image works again.
