### ISSUE TITLE
Improve uniqueness of menu item Id's

### ISSUE THREAD

**Issue by misfir3** [WebGoat/WebGoat#45]
Would be better to operate ID-less and that may happen in a refactor of the MenuView later, but for now, need to improve uniqueness of menu item id's (e.g. we have two 'Stage 1: Stored XSS' lessons and the ID is made deterministically from the name (only) currently.

**Comment by mayhew64** [comment]
We need to consider the ID-Less state and how that may or may not affect scanning tools.

**Comment by span** [comment]
I had a look at this and thought it should be possible to concatenate the `stageId` with the `lessonId` when generating the menu items. Would that be sufficient for now? I could provide a commit and pull request if so.

**Comment by misfir3** [comment]
Not everything has a stage, so that may be limited. Maybe better to prepend the category and/or use the ids (numerical) generated from the lessonMenu service. That's the short term. Longer term, I think I'd rather remove IDs out of the DOM on those menu items. That's a separate issue/effort though.

**Comment by span** [comment]
I completely agree on the long term. On the short term, I am still new to the code base of the application so I might have missed something obvious but here is my quick analysis of the possibilities at the moment.

I fint that prepending the category `name` would make the id's very long although they would have good semantics. 

`CrossSiteScriptingXSS`
`CrossSiteScriptingXSS-LABDBCrossSiteScriptingXSS`
`CrossSiteScriptingXSS-LABDBCrossSiteScriptingXSS-Stage1StoredXSS`

The stage id's generated in `LessonMenuService` seems to not be unique for stages. The other possibly unique property is the `link` for a lesson. The `link` is a string consisting of some special chars and integers, for example `#attack/152/900`. Parsing this into a unique integer where what we really would like seems to be `152` and the prepend it somewhere seems messy to me.

There is also the `cid` on the category that could be used. It could be prepended to the `lessonId` and then concatenate the `lessonId` with the `stageId`. We need the `lessonId` since a category can have multiple stages with same "base id". The result would be something like this.

`CrossSiteScriptingXSS`
`c88-LABDBCrossSiteScripting`
`c88-LABDBCrossSiteScripting-XSSStage1StoredXSS`

I think I might be more fond of the first attempt since it consistently uses what could be considered a parent id on the child.

**Comment by misfir3** [comment]
stale, closing
