### ISSUE TITLE
Missing lessons

### ISSUE THREAD

**Issue by MulleCreative** [WebGoat/WebGoat#462]
The lessons are missing in the user panel . I have tried alot of solutions even another browser. I installed Java and reinstalled WebGoat a million times. But nothing works.

**Comment by nbaars** [comment]
@MulleCreative which version of WebGoat are you using? Do you see any logs during the startup?

**Comment by nmoy93** [comment]
I struggling with the same thing. I've installed webgoat on mac using webgoat-container-7.1-exec.jar and when I attempt to login using the webgoat-admin account, all I see is a report card. No lessons.

**Comment by BetaMaxHeadroom** [comment]
I had a similar issue. I typed out the steps (poorly) here: https://github.com/WebGoat/WebGoat/issues/490 

My limited understanding is that WebGoat 7.1 works with Java 8. My Kali VM has Java 10. A bunch of things that are over my head happen, and it re-creates the issue.

However, if you install Java 8, and direct WebGoat 7.1 to use that instead of Java 10, it might help resolve your issue. My issue with 7.1 is over. 

I can't get version 8 to work since I can't find Java 9, and it requires Java 9. If you can find a source, please share it.

**Comment by nbaars** [comment]
Sorry, but we are not actively supporting WebGoat 7.1 all our time goes to developing WebGoat 8.
