### ISSUE TITLE
How to solve HTTP proxies?

### ISSUE THREAD

**Issue by zhangysh1995** [WebGoat/WebGoat#496]
I tried many combinations of case sensitivity but all failed. Is there any reference solution to the problems?

**Comment by tanskim** [comment]
don't change the method manually (by typing text "GET"), but use the combo box "method" in Zap Proxy and select "GET"

**Comment by Steve001** [comment]
Well...I've solved all the lessons in webgoat, if you need any help you can contract me...

**Comment by tanskim** [comment]
Hi,
I’m stuck on the web goat 8.0 sql injection challenge, when you have to login as « Tom » user. 
I rode the source code in java of this challenge on github, and I don’t see that being possible without create an heavy script who is in my opinion out of purpose.
The breach is on user name field in registry form. Any other fields are using setString method in java to format sql query who can’t provide an injection (I think 🤔)

Any hint ?

**Comment by nbaars** [comment]
@zhangysh1995 did you solve it?

**Comment by nbaars** [comment]
@tanskim it is indeed a challenging assignment, you need to perform multiple steps to get to the correct answer. I will add some unit tests in the SQL lessons to show how you can perform the attack

**Comment by auooo** [comment]
> don't change the method manually (by typing text "GET"), but use the combo box "method" in Zap Proxy and select "GET"

@tanskim , I have a question about this.  According to the [RFC7230](https://tools.ietf.org/html/rfc7230),  
 section 3.3, it says clearly about message body:

> The message body (if any) of an HTTP message is used to carry the
payload body of that request or response. The message body is
identical to the payload body unless a transfer coding has been
applied, as described in Section 3.3.1.
>
>  message-body = *OCTET
> The rules for when a message body is allowed in a message differ for requests and responses.
>
> The presence of a message body in a request is signaled by a
Content-Length or Transfer-Encoding header field. **Request message
framing is independent of method semantics**, even if the method does
not define any use for a message body.

So why I can't just change the method manually to "GET", and pass the param "changeMe" in message body instead of using the combo box "method" in Zap Proxy and select "GET" ,which moves the param "changeMe" to the http URI Scheme. In my opion, the effects of these two ways are supposed to be the same.

Really bothers me a lot~:confused:

**Comment by PiAil** [comment]
Can someone confirm that this challenge is solvable ? Tried everything I could think of, but nothing works.

For instance, I'm pretty sure this request should work:

    GET http://host:port/WebGoat/HttpProxies/intercept-request?Requests+are+tampered+easily=doesn't+matter+really HTTP/1.1

    User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0
    Accept: */*
    Accept-Language: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3
    Referer: https://192.168.99.100:8080/WebGoat/start.mvc
    Content-Type: application/x-www-form-urlencoded; charset=UTF-8
    X-Requested-With: XMLHttpRequest
    Content-Length: 0
    Connection: keep-alive
    Cookie: JSESSIONID=6A2B2D08D4D1042037D56E6F6D7E913D
    Host: host:port
    x-request-intercepted: true

But I keep getting this response:

    HTTP/1.1 200
    X-Application-Context: application:8080
    X-Content-Type-Options: nosniff
    X-XSS-Protection: 1; mode=block
    X-Frame-Options: DENY
    Content-Type: application/json;charset=UTF-8
    Date: Mon, 15 Jul 2019 14:27:20 GMT

    {
      "lessonCompleted" : false,
      "feedback" : "Please try again. Make sure to make all the changes. And case sensitivity may matter ... or not, you never know!",
      "output" : null
    }

Note: I tried several variations of the previous request, including:

1. changing url `+` to `%20`
2. moving content from url to the request body
3. changing `x-request-intercepted: true` to `X-Request-Intercepted: true` , based on the answer

Anyway, if there is indeed a solution, isn't it overly complicated for the second lesson ? I think it should be clearer.

**Comment by oezgan** [comment]
I would like to re-open this issue. I have tried a number of things which i would like to explain: 
Downloaded JAR file run the JAR and Intercepted the request as instructed, only difference i am using Burp Suite instead of ZAP

Changes done to the request are: 
`GET /WebGoat/HttpProxies/intercept-request HTTP/1.1`
`changeMe=Requests are tampered easily`
`x-request-intercepted:true`

For this i get the following result:

`{`
 ` "lessonCompleted" : false,`
 ` "feedback" : "Please try again. Make sure to make all the changes. And case sensitivity may matter ... or not, you never know!",`
 ` "output" : null`
`}`

So i was curious why this was not working and downloaded the source code from GIT added some 
log output with: `import org.apache.log4j.Logger`
compiled the code run the project as instructed. Used the same request from the Burp Suite repeater,
changing the `JSESSIONID` of course. And got the following result:

`{`
`  "lessonCompleted" : true,`
`  "feedback" : "Well done, you tampered the request as expected",`
`  "output" : null`
`}`

Now i was confused. So used a java decompiler (jd-gui) and de-compiled the JAR and checked the source.
Since i could not find any (real) difference. I exchanged the downloaded source code file with the de-compiled source code.  Built the project again. Used the same request from the Burp Suite Repeater changing the `JSESSIONID` and i got the following result:

`{`
 ` "lessonCompleted" : false,`
 ` "feedback" : "Please try again. Make sure to make all the changes. And case sensitivity may matter ... or not, you never know!",`
 ` "output" : null`
`}`

Now i am out of ideas what to do. Dear WebGoat team what would be the reason for this ? 
Thank you very much

**Comment by jugges** [comment]
Can confirm it works with the following request:
```
GET /WebGoat/HttpProxies/intercept-request?changeMe=Requests+are+tampered+easily HTTP/1.1

Host: localhost:8080

User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0

Accept: */*

Accept-Language: en-US,en;q=0.5

Accept-Encoding: gzip, deflate

Referer: http://localhost:8080/WebGoat/start.mvc

X-Requested-With: XMLHttpRequest

x-request-intercepted: true

Cookie: JSESSIONID=4AB3FBE0F0CB058DFDB085DE0BD58B74

Connection: close

Content-Type: application/x-www-form-urlencoded

Content-Length: 37
```

**Comment by vitorTest** [comment]
I can confirm there's no bug, the lesson is working right. 
What I could observe from your answers is that you have to specify better what is
being passed through the method GET.

**Comment by vitorTest** [comment]
I can confirm there's no bug, the lesson is working right.
What I could observe from your answers is that you have to specify better what is
being passed through the method GET.

And I used ZAP, modifying the Header directly the text at the tab Break. I don't know if it was an issue that was fixed, but by now it was working just fine. :)

**Comment by shmooth** [comment]
I had a lot of trouble with this exercise, and also Zap, so I used Charles, and finally got it working.

Once Charles has intercepted the request, go into 'Edit Request' then:

1. Form, and delete the 'changeMe=doesn't really matter' line (deleting the POST data)
2. URL, and change the POST to a GET in the dropdown
3. URL, and 'Add' the name/value pair of 'changeMe/Requests are tampered easily' (adding the new/updated query string param/value) 
3. Headers, and paste the line 'x-request-intercepted:true' just after the 'Content-type' line

'Execute'/continue the request.

The main problem in doing this with Charles, that I can tell, is that Charles has an ambiguous UI. e.g. The 'Form' tab will change to 'Text' sometime after you change the request from POST to GET, but the form data will not get added as a GET/query string param/value pair (which is not necessarily wrong). 

I'd guess a similar situation exists with Zap -- i.e. explicitly construct the request if you have to, without using the wizards, then go back and figure out how the wizards are working.

For Charles, the ultimate state of the request appears to be whatever is in the 'Headers' tab at the moment you press 'Execute'.
