### ISSUE TITLE
WebGoat 8.0.0.M21 shows error

### ISSUE THREAD

**Issue by SiThu9** [WebGoat/WebGoat#508]
Dear WebGoat team,
I received unexpected error message for latest release. Please see my attached image.
How should I do to get the lessons. Thanks.
![capturewebgoat8](https://user-images.githubusercontent.com/29085408/43042739-6f59aacc-8db6-11e8-92c1-183eceb871b9.JPG)

**Comment by jaymanza** [comment]
Hi WebGoat team,
I am having the exact same issue as SiThu9.
I have attached screen shots of the error and also java version.
Please advise, and thank you!

![snip20180722_14](https://user-images.githubusercontent.com/41549755/43048477-647bf060-8de8-11e8-989d-6e8651a2674a.png)
![snip20180722_15](https://user-images.githubusercontent.com/41549755/43048478-70b1ebbe-8de8-11e8-9de8-5693797d3f2d.png)

**Comment by nbaars** [comment]
@SiThu9 At first I thought you were using WebGoat 7 because of the black background in the menu. However looking at the lesson you are indeed starting WebGoat 8. Did you happen to first start WebGoat 7 and then start WebGoat 8? I know there were issues in the past with this combination @misfir3 can you remember this? Was it enough to clear the browser cache?

**Comment by SiThu9** [comment]
Hi @nbaars Thanks for your reply. Yes, First, I installed Webgoat 7 and got problem. So I uninstalled 7 and installed Webgoat 8 again. Both got problems.

**Comment by nbaars** [comment]
@SiThu9 do you see an error in the console? Did you try to clear all the caches from your browser? I indeed remember the same issue while both working on 7 and 8 in the beginning of release 8.

**Comment by krammk96** [comment]
thankyou u so much for the solution.Working great!!!!!!!!!!!!!!!!
