### ISSUE TITLE
Spring Boot 2 upgrade

### ISSUE THREAD

**Issue by zubcevic** [WebGoat/WebGoat#565]
Perhaps it is time for an upgrade of the software from Spring Boot 1 to Spring Boot 2.

The challenging parts will be in the Spring Actuator and ThymeLeaf redesigns that will be required.

**Comment by woccnews** [comment]
This would be great particularly because the integration of spring-boot-devtools does not work anymore in Java 11 as the old V1.x spring-boot-dev uses the old class loader and gets a ClassCastException. An update to the latest Spring Boot 2 should resolve this issue (see below in further detail) which occurs if one tries to follow the recommendation given in the WebGoat Wiki (https://github.com/WebGoat/WebGoat/wiki/Simplified-development) and install the Spring Boot Developer Tools.
The issue in detail is (stack trace excerpt):

java.lang.ClassCastException: jdk.internal.loader.ClassLoaders$AppClassLoader (in module: java.base) cannot be cast to java.net.URLClassLoader (in module: java.base)
...
Caused by: java.lang.ClassCastException: jdk.internal.loader.ClassLoaders$AppClassLoader (in module: java.base) cannot be cast to java.net.URLClassLoader (in module: java.base)

<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-devtools</artifactId>
            <optional>true</optional>
        </dependency>

**Comment by nbaars** [comment]
Also revert the remark on https://github.com/WebGoat/WebGoat/wiki/Simplified-development
after the move

**Comment by zubcevic** [comment]
#667
