### ISSUE TITLE
secure passwords exercise suggestion

### ISSUE THREAD

**Issue by zubcevic** [WebGoat/WebGoat#580]
I have looked at the new secure passwords exercise and discussed it with some people. 
- Some ask questions whether or not these passwords will be logged and are a way of tricking you into providing passwords. 
- Others indicate that it would be better to hide the passwords if you want to test your passwords in front of some other people

For this last concern, I have created a branch in my forked repository:
[hidden password changes](https://github.com/WebGoat/WebGoat/compare/develop...zubcevic:secure-password-hidden)

If you  @MaxGeldner  agree, you or I can make a pull request for this repo.

**Comment by MaxGeldner** [comment]
Hello,

I agree with the concerns. The changes made in your branch are good. You can create a pull request for them like this.

For the first concern: We used an open source library for the password strength checks. Users are invited to read the [library documentation](https://blogs.dropbox.com/tech/2012/04/zxcvbn-realistic-password-strength-estimation/) or checkout the [code on github](https://github.com/dropbox/zxcvbn). I honestly didn't take a look into the library since another team member implemented it into WebGoat. But I think there is no thing like logging passwords implemented.

**Comment by MarvinSchoening** [comment]
Maybe it is a good idea to have something like a radio button with confirmation to switch between hiding and showing your password so you could showcase your input if you want to or hide it if you dont want to

**Comment by zubcevic** [comment]
Good idea, someone else also suggested this. I'll look into that in a few days

**Comment by zubcevic** [comment]
merged into develop
