### ISSUE TITLE
After login, there is no default lesson

### ISSUE THREAD

**Issue by davewichers** [WebGoat/WebGoat#72]
You kind of get a blank screen with just the menus on the side. Seems like you should default to go to the Http Basics lesson, which is what previous WebGoat used to do.

**Comment by misfir3** [comment]
Thanks for creating this officially. This has been on my mental //TODO list, but did not get it noted down here yet.

**Comment by mayhew64** [comment]
Let's default it to "How to Work with WebGoat"

**Comment by misfir3** [comment]
@mayhew64 - I set up (not committed or PR'd yet) a ['well call it a]'page' that would show up at start.mvc#welcome (which you would now be redirected to on login). Since 'How to Work with Webgoat' is automatically 'completed' on viewing the page and the page would come up by default, I propose that we just move that content over to the template/page and remove 'How to Work with WebGoat' as a plugin lesson.  Thoughts?

**Comment by mayhew64** [comment]
I would prefer to have it default to the first lesson, i.e. lesson with the lowest rank.  This way, the user can reconfigure what lesson is defaulted from the webgoat.properties.  Even if there are no plugins installed, I put the admin screens in the webgoat-container, so the report card screen would be the default in that case.

**Comment by dougmorato** [comment]
@misfir3 pushed code to redirect to first lesson upon login
