### ISSUE TITLE
Unclear objective of vulnerable components practical assignment

### ISSUE THREAD

**Issue by winter3angle** [WebGoat/WebGoat#766]
Hi pals,
It's quite unclear what user should do to pass the only practical assignment in the A9 "Vulnerable Components" section. There are just some advises to carefully read writeup and PoC from lesson 11, but final goal is not specified. Blindly copy-pasting payload from writeup doesn't work and emits nothing, maybe due to #725 
Probably it would be good to say, for example, that one should pop cmd or calc on to complete this. That's just example, don't know how to achieve this using docker image (probably it is not possible).

**Comment by nbaars** [comment]
@zubcevic you did some work on this lesson recently right? Can we close this issue?

**Comment by zubcevic** [comment]
at least the part of having two versions of jQuery icw RequireJS is working again. So that should be pretty clear now. The other assignment just works normal. And owasp dependency-check example has been updated. So I think we'll close it for now and wait if there are still issues with the latest from develop.
