### ISSUE TITLE
Can't login through Zap Proxy

### ISSUE THREAD

**Issue by Randomizer123** [WebGoat/WebGoat#856]
Hello,

I am running WebGoat in port 8085 and ZAP proxy in port 8000. If i proxy the traffic it works and i can access to the WebGoat login page but i can´t login. I see the POST request, the login is working and i am getting redirected properly

POST request, i get redirected to /welcome.mvc
![image](https://user-images.githubusercontent.com/67732929/86336148-be568180-bc4f-11ea-95e4-f2a29b77592c.png)

GET request to /welcome.mvc, i get redirected to the login page instead of accessing to the application
![image](https://user-images.githubusercontent.com/67732929/86336196-d0d0bb00-bc4f-11ea-937e-cf1cb6dc31cf.png)

This behavior is only happening when using ZAP. It works fine if i don´t proxy the traffic or if i proxy it through Burp Proxy. Also i have tried with the standalone package (8.1.0) and docker.

**Comment by zubcevic** [comment]
If you do not have the cookie, you get redirected to the login page. So the behaviour from WebGoat is correct. 
The question is why ZAP didn't handle the Set-Cookie from the first request. But that might be related to your script or browser. Or else it is a ZAP issue and you need to report it there. I think you can close the issue here.
