### ISSUE TITLE
Is WebGoat supposed to be used by multiple users simultaneously?

### ISSUE THREAD

**Issue by haohaolee** [WebGoat/WebGoat#892]
Hi folks,
We have deployed an instance of WebGoat-8.0 using the docker-compose.yml for education purpose.
But we found in SQL Injection (intro) lessons, after some users have finished the lesson, other users cannot succeed. e.g. SqlInjection.lesson/3 `Now try to modify the scheme by adding the column "phone" (varchar(20)) to the table "employees".`
After someone has inserted a column called phone, no other one can insert a new column called phone.

Did I miss something? Thanks

**Comment by zubcevic** [comment]
The 8.0 version as the latest 8.1 or latest develop versions are not 100% fit for running all assignments concurrently. Especially this one.
However there is a simple solution in this case. On page 3 on DML you can use the exercise a second time around but now for the reason of dropping this column. 
Maybe for now we can add that as a hint. 
Otherwise we need some major change I guess.

**Comment by haohaolee** [comment]
Got it. Thank you for your explanation.
