### ISSUE TITLE
I am NOT able to browse WebGoat.

### ISSUE THREAD

**Issue by alijoodaki** [WebGoat/WebGoat#893]
Dear Team
Hi;
I can setup webgoat on my win 10 and reach it via http://127.0.0.1:8080/webgoat/login. But the point is that I don't want its service run on my own win, thus I have setup centos7.6 minimal on VM and run webgoat service on that, but the problem is that when I browse http://vmIP:8080/webgoat/login, it doesn't return the webgoat login page,
I turned off firewall on both sides(Centos and win 10), still the same problem.
Kindly help me.

**Comment by nbaars** [comment]
@alijoodaki please use http://127.0.0.1:8080/*W*eb*G*oat/ mind the capital letter 'W' and 'G'

**Comment by alijoodaki** [comment]
> @alijoodaki please use http://127.0.0.1:8080/WebGoat/ mind the capital letter 'W' and 'G'

I do type them in capital letters, actually I wanna browse the service run on my Centos, thus I have to enter its IP, don't I ?

**Comment by nbaars** [comment]
Ah sorry, this is probably due to the fact that by default `java -jar webgoat.jar` only binds to localhost, if you use: `java -jar webgoat.jar server.address=0.0.0.0` it will bind to all interfaces. If you still cannot connect take a look at the networking you selected in the VM (bridge, nat etc). Bridge mode should work been a long time since I set it up with a VM.

You can also use the Docker image we provide

**Comment by nbaars** [comment]
@alijoodaki maybe this can help: https://medium.com/@develouise/getting-started-with-webgoat-and-webwolf-using-jar-d06431883cc2?
