### ISSUE TITLE
Vulnerable components lesson

### ISSUE THREAD

**Issue by zinzloun** [WebGoat/WebGoat#922]
Server is WebGoat 8.1.0 jar file.
Having trouble to solve the assignment I took a look at the source code of the lesson decompiling the JAR:

```java
package org.owasp.webgoat.vulnerable_components;

import com.thoughtworks.xstream.XStream;
import com.thoughtworks.xstream.converters.ConversionException;
import com.thoughtworks.xstream.io.HierarchicalStreamDriver;
import com.thoughtworks.xstream.io.xml.DomDriver;
import org.owasp.webgoat.assignments.AssignmentEndpoint;
import org.owasp.webgoat.assignments.AttackResult;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class VulnerableComponentsLesson extends AssignmentEndpoint {
  @PostMapping({"/VulnerableComponents/attack1"})
  @ResponseBody
  public AttackResult completed(@RequestParam String payload) {
    XStream xstream = new XStream((HierarchicalStreamDriver)new DomDriver());
    xstream.setClassLoader(Contact.class.getClassLoader());
    xstream.processAnnotations(Contact.class);
    try {
      Contact expl = (Contact)xstream.fromXML(payload);
      return success(this).feedback("vulnerable-components.fromXML").feedbackArgs(new Object[] { expl.toString() }).build();
    } catch (ConversionException ex) {
      if (ex.getMessage().contains("Integer"))
        return success(this).feedback("vulnerable-components.success").build(); 
      return failed(this).feedback("vulnerable-components.close").build();
    } 
  }
}
```
So passing the following payload

```xml
<contact><Integer/></contact>
```
permitted to mark the assignment as solved. 
Of course I read the article: https://www.pwntester.com/blog/2013/12/23/rce-via-xstream-object-deserialization38
and as far as I understand since <i>XStream.fromXML will throw a cast exception</i> but eventually the payload containing a serialized <i>TreeSet<Comparable></i> object will be executed, since the exception message contains:
<i>java.lang.UNIXProcess cannot be cast to java.lang.<b>Integer</b></i> the <i>Goat</i> assumes that we have submitted the correct payload if the error message contains the word <b>Integer</b>.  Is the application's behaviour intentional or can be consider as a sort of work-around? I don't want to bother you, but since I don't master Java very well I'd like to know if my assumption is correct.

**Comment by avivmu** [comment]
You can view the most updated version of this file [in github](https://github.com/WebGoat/WebGoat/blob/develop/webgoat-lessons/vulnerable-components/src/main/java/org/owasp/webgoat/vulnerable_components/VulnerableComponentsLesson.java). It also [returns a success](https://github.com/WebGoat/WebGoat/blob/develop/webgoat-lessons/vulnerable-components/src/main/java/org/owasp/webgoat/vulnerable_components/VulnerableComponentsLesson.java#L66) if there's an exception which looks wrong.
The lesson was updated because of [this issue](https://github.com/WebGoat/WebGoat/issues/845).
You can [build from source](https://github.com/WebGoat/WebGoat#3-run-from-the-sources) to have the latest version (the _develop_ branch in git)
Or [use docker](https://github.com/WebGoat/WebGoat#using-docker-run) since [it was updated](https://hub.docker.com/r/webgoat/goatandwolf) about 20 days ago.

**Comment by zubcevic** [comment]
The fix which is in develop can be retrieved with the develop label:

docker run -p 8080:8080 -p 9090:9090 -e TZ=Europe/Amsterdam webgoat/goatandwolf:develop
