### ISSUE TITLE
SQL-Lesson 5 (Advanced) not showinf "complete" icon

### ISSUE THREAD

**Issue by mwithi** [WebGoat/WebGoat#996]
Note: of course I've navigated in and out the chapter and restarted the server many times so far before to open the issue

![image](https://user-images.githubusercontent.com/2938553/117587417-29010500-b11e-11eb-8740-52bda712d7bd.png)

**Comment by aolle** [comment]
Hello,

I am using the latest release and I recently completed the SQL Injection (advanced) lesson and it was marked as completed.

If you're using the latest release, I think that you've a challenge pending to be solved. 

For example, the assessment #5 has more than one challenge, even if you have it in green -because you solved one of them- you have to solve the remaining challenges. Once all challenges are solved, you will see the lesson marked as complete.

Regards.
